sudo: false
language: python
os: linux
python:
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"
matrix:
  allow_failures:
    - python: "3.6-dev"
    - python: "3.7-dev"

env:
  - JDK=oraclejdk8
  - JDK=openjdk8

before_install:
  - jdk_switcher use $JDK
  - java -version
  - python --version
  # Open Fortran Parser
  - git clone "https://github.com/OpenFortranProject/open-fortran-parser" "../open-fortran-parser"
  # Open Fortran Compiler
  - git clone "https://github.com/codethinklabs/ofc" "../open-fortran-compiler"
  - cd "../open-fortran-compiler" && make && cd -
  - export PATH="${PATH}:$(pwd)/../open-fortran-compiler"
  # FFB-MINI app
  - git clone "https://github.com/mbdevpl/ffb-mini" "../ffb-mini" --branch ofp_tests

install:
  # dependencies
  - pip install -U pip
  - pip install -U -r dev_requirements.txt
  # Java
  - python open_fortran_parser/dev_dependencies.py
  - export CLASSPATH="${CLASSPATH}:$(pwd)/lib/*"
  - ant
  - export CLASSPATH="${CLASSPATH}:$(pwd)/dist/*"
  # Java tests
  - wget "https://search.maven.org/remotecontent?filepath=org/jacoco/org.jacoco.agent/0.7.9/org.jacoco.agent-0.7.9-runtime.jar" -O "lib/org.jacoco.agent-0.7.9-runtime.jar"
  - wget "https://oss.sonatype.org/content/repositories/snapshots/org/jacoco/org.jacoco.cli/0.7.10-SNAPSHOT/org.jacoco.cli-0.7.10-20170921.145522-19-nodeps.jar" -O "lib/org.jacoco.cli-0.7.10-20170921.145522-19-nodeps.jar"

script:
  - TEST_PACKAGING=1 TEST_DEPENDENCIES=1 python -m coverage run --branch --source . -m unittest discover --verbose

after_success:
  - python -m coverage report --show-missing
  #- bash <(curl -s https://codecov.io/bash) -cF python
  - coveralls
  - pip install -U codecov
  - java -jar "lib/org.jacoco.cli-0.7.10-20170921.145522-19-nodeps.jar" report "jacoco.exec" --classfiles "bin/" --csv "jacoco.csv" --html "jacoco/" --sourcefiles "src/" --xml jacoco.xml
  - cat "jacoco.csv"
  #- bash <(curl -s https://codecov.io/bash) -cF java
  - codecov
  - python -m pylint --load-plugins=pylint.extensions.mccabe --docstring-min-length 5 --no-docstring-rgx "^(test)?_|.*Tests$" --unsafe-load-any-extension y --output-format colorized  --reports y $(find . -name "*.py")

notifications:
  slack:
    secure: "OiXc/9CvAVd1l3xWTP554GzPe7ba6cBUHzLLHi4siEW0TDCDeJAzRrFbA/Ei2OTBqVX5p6b4uqeuPCc+IIYhcNDZa4tvEAAyfMIttKEEiEE7qMESxaqXkYQo0IIDu2FVjNjvqZlOfzc9kjFL2J2W3uCd/yivd/WOIoIijkU1HiFfN7wk6e+1ATUIyPXrNJNDYpE2/gKJhMVNHexjEQkeNgGN4eoAU/2cTdwI23SkHCsPgxbgCSMCUn0N/ZsTEgu/zzVFUBlqzzDZKR+fHmrCv7pLHSkIe2WROlbAFyg0AzIEJwhTLbZLOC9Xh1FLhigYvNDaZsOFUnlSEwmSjegvtnXLQkJ2vtSS7xf2UaLdc4w+kgv6If7369IICHgi59X97C8dT9W+YeZoidkINiMuijmCkTKqKF+DhpOx6x2bt6Pk91RscIjwqamb1a0SvMhgqtfpYQz/UkyDadC3g2BsHdg0l+K6ZmEWtfJUMAVctsr8dvwg2KlwrfX5V4+ecwzluz5aL7jYBzXRlgO83ulvM+xaS/9+CGMn08w6ipCjK2xrD4ZKMnoHBr2s+ijceoYINg9nDefNknV9C2Ja/pjgMCtWKZNlX/PkhbOq0oLBBsoUM3Mp1JgP86I88H6TSCRFk8ASV/ghZeaAr8k7AzZi2TAzGFh90KGrlw6aNzvqVak="
  email: false
